/*
  Warnings:

  - The values [HHEALTHY_HABITS] on the enum `Tags` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Tags_new" AS ENUM ('HEALTH', 'FITNESS', 'NUTRITION', 'WELLNESS', 'MENTAL_HEALTH', 'LIFESTYLE', 'HEALTHY_HABITS', 'SELF_CARE', 'WORK_LIFE_BALANCE', 'MINDFULNESS', 'MEDITATION', 'BURNOUT_PREVENTION', 'SUBSTANCE_ABUSE', 'DIGITAL_DETOX', 'SLEEP_HEALTH', 'HEALTHY_EATING', 'WORK_STRESS', 'TRAUMA', 'SOCIAL_ANXIETY', 'DEPRESSION', 'ANXIETY', 'LOW_SELF_ESTEEM', 'LONELINESS', 'DRIEF_AND_LOSS', 'PANIC_ATTACKS', 'COUPLES_THERAPY', 'FAMILY_THERAPY', 'INDIVIDUAL_THERAPY', 'GROUP_THERAPY', 'PSYCHOTHERAPY', 'COGNITIVE_BEHAVIORAL_THERAPY', 'DIALOGUE_THERAPY', 'PSYCHOANALYSIS', 'HUMANISTIC_THERAPY', 'EXISTENTIAL_THERAPY', 'BEHAVIORAL_THERAPY', 'ART_THERAPY', 'MUSIC_THERAPY', 'PLAY_THERAPY', 'DRAMA_THERAPY', 'NARRATIVE_THERAPY', 'SOLUTION_FOCUSED_THERAPY', 'MINDFULNESS_BASED_STRESS_REDUCTION', 'ACCEPTANCE_AND_COMMITMENT_THERAPY', 'EMOTION_FOCUSED_THERAPY', 'INTERPERSONAL_THERAPY', 'SCHEMA_THERAPY', 'TRANSACTIONAL_ANALYSIS', 'SYSTEMIC_THERAPY', 'FAMILY_SYSTEMS_THERAPY', 'MULTICULTURAL_THERAPY', 'CULTURAL_THERAPY', 'CROSS_CULTURAL_THERAPY', 'TRANSCULTURAL_THERAPY', 'SPIRITUAL_THERAPY', 'TRANSPERSONAL_THERAPY', 'SOMATIC_THERAPY', 'BODY_CENTRED_THERAPY', 'RELATIONSHIPS', 'COMMUNICATION', 'CONFLICT_RESOLUTION', 'EMOTIONAL_INTELLIGENCE', 'POSITIVE_PSYCHOLOGY', 'OTHER');
ALTER TABLE "Community" ALTER COLUMN "tags" DROP DEFAULT;
ALTER TABLE "Post" ALTER COLUMN "tags" DROP DEFAULT;
ALTER TABLE "Community" ALTER COLUMN "tags" TYPE "Tags_new"[] USING ("tags"::text::"Tags_new"[]);
ALTER TABLE "Post" ALTER COLUMN "tags" TYPE "Tags_new"[] USING ("tags"::text::"Tags_new"[]);
ALTER TYPE "Tags" RENAME TO "Tags_old";
ALTER TYPE "Tags_new" RENAME TO "Tags";
DROP TYPE "Tags_old";
ALTER TABLE "Community" ALTER COLUMN "tags" SET DEFAULT ARRAY[]::"Tags"[];
ALTER TABLE "Post" ALTER COLUMN "tags" SET DEFAULT ARRAY[]::"Tags"[];
COMMIT;
