-- CreateEnum
CREATE TYPE "Tags" AS ENUM ('HEALTH', 'FITNESS', 'NUTRITION', 'WELLNESS', 'MENTAL_HEALTH', 'LIFESTYLE', 'HHEALTHY_HABITS', 'SELF_CARE', 'WORK_LIFE_BALANCE', 'MINDFULNESS', 'MEDITATION', 'BURNOUT_PREVENTION', 'SUBSTANCE_ABUSE', 'DIGITAL_DETOX', 'SLEEP_HEALTH', 'HEALTHY_EATING', 'WORK_STRESS', 'TRAUMA', 'SOCIAL_ANXIETY', 'DEPRESSION', 'ANXIETY', 'LOW_SELF_ESTEEM', 'LONELINESS', 'DRIEF_AND_LOSS', 'PANIC_ATTACKS', 'COUPLES_THERAPY', 'FAMILY_THERAPY', 'INDIVIDUAL_THERAPY', 'GROUP_THERAPY', 'PSYCHOTHERAPY', 'COGNITIVE_BEHAVIORAL_THERAPY', 'DIALOGUE_THERAPY', 'PSYCHOANALYSIS', 'HUMANISTIC_THERAPY', 'EXISTENTIAL_THERAPY', 'BEHAVIORAL_THERAPY', 'ART_THERAPY', 'MUSIC_THERAPY', 'PLAY_THERAPY', 'DRAMA_THERAPY', 'NARRATIVE_THERAPY', 'SOLUTION_FOCUSED_THERAPY', 'MINDFULNESS_BASED_STRESS_REDUCTION', 'ACCEPTANCE_AND_COMMITMENT_THERAPY', 'EMOTION_FOCUSED_THERAPY', 'INTERPERSONAL_THERAPY', 'SCHEMA_THERAPY', 'TRANSACTIONAL_ANALYSIS', 'SYSTEMIC_THERAPY', 'FAMILY_SYSTEMS_THERAPY', 'MULTICULTURAL_THERAPY', 'CULTURAL_THERAPY', 'CROSS_CULTURAL_THERAPY', 'TRANSCULTURAL_THERAPY', 'SPIRITUAL_THERAPY', 'TRANSPERSONAL_THERAPY', 'SOMATIC_THERAPY', 'BODY_CENTRED_THERAPY', 'RELATIONSHIPS', 'COMMUNICATION', 'CONFLICT_RESOLUTION', 'EMOTIONAL_INTELLIGENCE', 'POSITIVE_PSYCHOLOGY', 'OTHER');

-- AlterTable
ALTER TABLE "Community" ADD COLUMN     "tags" "Tags"[] DEFAULT ARRAY[]::"Tags"[];

-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "tags" "Tags"[] DEFAULT ARRAY[]::"Tags"[];

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "interests" TEXT;

-- CreateTable
CREATE TABLE "PostReaction" (
    "userId" INTEGER NOT NULL,
    "postId" TEXT NOT NULL,
    "reaction" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PostReaction_pkey" PRIMARY KEY ("userId","postId","reaction")
);

-- CreateTable
CREATE TABLE "CommentReaction" (
    "userId" INTEGER NOT NULL,
    "commentId" TEXT NOT NULL,
    "reaction" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CommentReaction_pkey" PRIMARY KEY ("userId","commentId","reaction")
);

-- AddForeignKey
ALTER TABLE "PostReaction" ADD CONSTRAINT "PostReaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PostReaction" ADD CONSTRAINT "PostReaction_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommentReaction" ADD CONSTRAINT "CommentReaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommentReaction" ADD CONSTRAINT "CommentReaction_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "Comment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
